### PR TITLE
Correct capability report for Gen12 SCC prediction direction

### LINKED ISSUE #1401: Encoder can not insert normal B frames in HEVC SCC related profiles in low power mode on TGL.
## System information
- GPU information(`lspci -nn | grep -E 'VGA|isplay`): TGL

### Describe the current behavior
The HEVC SCC related profiles can not encode normal B frames. But in VAConfigAttribPredictionDirection query,  it returns both VA_PREDICTION_DIRECTION_PREVIOUS and VA_PREDICTION_DIRECTION_FUTURE, which means it can support normal B frames.

### Describe the expected behavior
Add the support for normal B frames, or correct the query result.

## Debug information
gst-launch-1.0 -vf videotestsrc num-buffers=30 ! video/x-raw,format=NV12,width=800,height=600 ! vaapih265enc tune=low-power rate-control=cqp max-bframes=1 refs=2 ! video/x-h265,profile=screen-extended-main ! h265parse ! filesink location=out.h265

fails and print log:

[CODEC]:CRITICAL - ValidateRefFrameData:2129: MOS returned error, eStatus = 0x2
[CODEC]:CRITICAL - SetSliceStructs:1297: MOS returned error, eStatus = 0x2
[CODEC]:CRITICAL - InitializePicture:2294: MOS returned error, eStatus = 0x2
[CODEC]:CRITICAL - InitializePicture:3099: MOS returned error, eStatus = 0x2
[CODEC]:CRITICAL - ExecuteEnc:4869: Encoding initialization failed.
[CODEC]:CRITICAL - Execute:613: MOS returned error, eStatus = 0x2
[LIBVA]:CRITICAL - EncodeInCodecHal:406: DDI:Failed in Codechal!
[LIBVA]:CRITICAL - EndPicture:81: DDI:DdiEncode_EncodeInCodecHal return failure.

### PR DESCRIPTION
**Pull request by Xiaogangli-intel**
1. Correct the capability report for SCC prediction direction on Gen12, SCC only support I/P/Low Delay B on Gen12.
2. Fixes #1401

### CODE REVIEW

File: media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp [hunk 1]
```diff
@@ -532,7 +532,18 @@ VAStatus MediaLibvaCapsDG2::GetPlatformSpecificAttrib(VAProfile profile,
...
+            {
+                *value = VA_PREDICTION_DIRECTION_PREVIOUS | VA_PREDICTION_DIRECTION_FUTURE | VA_PREDICTION_DIRECTION_BI_NOT_EMPTY;
+            }
+            else
+            {
+                // Here we set
+                // VAConfigAttribPredictionDirection: VA_PREDICTION_DIRECTION_PREVIOUS together with
+                // VAConfigAttribEncMaxRefFrames: L0 != 0, L1 !=0
+                // to indicate SCC only supports I/P/low delay B
+                *value = VA_PREDICTION_DIRECTION_PREVIOUS;
```
Comment (xhaihao) [inline media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp:545]: VA_PREDICTION_DIRECTION_BI_NOT_EMPTY should be set for low-delay B, otherwise user won't know reference list 1 should be set too when constructing reference lists.

@XinfengZhang  @HeJunyan Is my understanding right ?

Comment (HeJunyan) [reply media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp:545]: VA_PREDICTION_DIRECTION_BI_NOT_EMPTY is set when L0 only frames should not exist. So for P frame, we need to add a duplicated L1 and construct LDB. But for B frames, which already have L1, this flag has no big effect.

Comment (xhaihao) [reply media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp:545]: How do you know l1==l0 ? for B frame ? @HeJunyan

Comment (Xiaogangli-intel) [reply media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp:545]: let us align again:
| Supported Type | EncMaxRefFrames Setting | PredictionDirection Setting                                                                                |
| -------------- | ----------------------- | ---------------------------------------------------------------------------------------------------------- |
| I/P            | l0 != 0, l1 = 0         | VA_PREDICTION_DIRECTION_PREVIOUS                                                                           |
| I/P/LDB        | l0 != 0, l1 != 0        | VA_PREDICTION_DIRECTION_PREVIOUS                                                                           |
| I/P/B          | l0 != 0, l1 != 0        | VA_PREDICTION_DIRECTION_PREVIOUS \| VA_PREDICTION_DIRECTION_FUTURE                                         |
| I/LDB/B        | l0 != 0, l1 != 0        | VA_PREDICTION_DIRECTION_PREVIOUS \| VA_PREDICTION_DIRECTION_FUTURE \| VA_PREDICTION_DIRECTION_BI_NOT_EMPTY |
| I/LDB          | l0 != 0, l1 != 0        | VA_PREDICTION_DIRECTION_PREVIOUS \| VA_PREDICTION_DIRECTION_BI_NOT_EMPTY                                   |

Is this make sense?

Comment (xhaihao) [reply media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp:545]: Got it, thanks!

**Review by xhaihao — APPROVED** [review]
LGTM

File: media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp (hunk 1 above)
Comment (HeJunyan) [reply media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp:545]: The VAEncSliceParameterBufferHEVC has ref_pic_list0 and ref_pic_list1 respectively.  The good way, maybe, not let the ref pictures in L0+L1 surplus 3.

Comment (HeJunyan) [reply media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp:545]: Right, thanks.

File: media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp [hunk 2]
```diff
@@ -532,7 +532,18 @@ VAStatus MediaLibvaCapsDG2::GetPlatformSpecificAttrib(VAProfile profile,
         }
         case VAConfigAttribPredictionDirection:
         {
-            *value = VA_PREDICTION_DIRECTION_PREVIOUS | VA_PREDICTION_DIRECTION_FUTURE | VA_PREDICTION_DIRECTION_BI_NOT_EMPTY;
+            if (!IsHevcSccProfile(profile))
+            {
+                *value = VA_PREDICTION_DIRECTION_PREVIOUS | VA_PREDICTION_DIRECTION_FUTURE | VA_PREDICTION_DIRECTION_BI_NOT_EMPTY;
```
Comment (XinfengZhang) [inline media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp:537]: no P frame support

File: media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp [hunk 3]
```diff
@@ -916,7 +927,18 @@ VAStatus MediaLibvaCapsDG2::CreateEncAttributes(
     if (IsHevcProfile(profile))
     {
         attrib.type = (VAConfigAttribType) VAConfigAttribPredictionDirection;
-        attrib.value = VA_PREDICTION_DIRECTION_PREVIOUS | VA_PREDICTION_DIRECTION_FUTURE | VA_PREDICTION_DIRECTION_BI_NOT_EMPTY;
+        if (!IsHevcSccProfile(profile))
+        {
+            attrib.value = VA_PREDICTION_DIRECTION_PREVIOUS | VA_PREDICTION_DIRECTION_FUTURE | VA_PREDICTION_DIRECTION_BI_NOT_EMPTY;
```
Comment (XinfengZhang) [inline media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp:932]: not support P frame?

**Review by XinfengZhang — COMMENTED** [review]
so, for the HEVC normal profiles, only support I LDB RAB, no P frame 
HEVC SCC support I P LDB, right?

**Review by XinfengZhang — APPROVED** [review]

File: media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp (hunk 2 above)
Comment (Xiaogangli-intel) [reply media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp:537]: corrected.

File: media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp (hunk 3 above)
Comment (Xiaogangli-intel) [reply media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp:932]: Gen12 doesn't support P frame, corrected the change.

**Comment by xhaihao** [comment]
@Xiaogangli-intel  If the driver can advertise the capability correctly, we may remove a WA from our cartwheel-ffmpeg (see https://github.com/intel-media-ci/cartwheel-ffmpeg/pull/140). You may run the command below for testing. 

$ ffmpeg -hwaccel vaapi -init_hw_device vaapi=hw:/dev/dri/renderD129 -hwaccel_output_format vaapi -v verbose -f rawvideo -pix_fmt 0yuv -s:v 1920x1080 -i  ayuv.yuv -vf 'format=0yuv,hwupload' -an -c:v hevc_vaapi -profile:v scc -rc_mode CQP -qp 28 -g 30 -slices 1 -low_power 1 -y out.hevc

**Comment by Xiaogangli-intel** [comment]
> @Xiaogangli-intel If the driver can advertise the capability correctly, we may remove a WA from our cartwheel-ffmpeg (see [intel-media-ci/cartwheel-ffmpeg#140](https://github.com/intel-media-ci/cartwheel-ffmpeg/pull/140)). You may run the command below for testing.
> 
> $ ffmpeg -hwaccel vaapi -init_hw_device vaapi=hw:/dev/dri/renderD129 -hwaccel_output_format vaapi -v verbose -f rawvideo -pix_fmt 0yuv -s:v 1920x1080 -i ayuv.yuv -vf 'format=0yuv,hwupload' -an -c:v hevc_vaapi -profile:v scc -rc_mode CQP -qp 28 -g 30 -slices 1 -low_power 1 -y out.hevc

Thanks, @xhaihao, #1429 will fix this. the reason is SCC is using the sharing attribute list.
