### PR TITLE
[Encode] Fixed VP9 444 frame header

### LINKED ISSUE #1074: Encode: VP9: Failed to create the correct VP8 frame header for 4:4:4 profile.
When the 4:4:4 chrome is seleced, the sub_sampling_x/y is not very correct in VP9 frame header.

I notice:

In  linux/common/codec/ddi/media_libvpx_vp9.cpp:

96     if ((codecProfile == VP9_PROFILE_1) ||
97         (codecProfile == VP9_PROFILE_3))
98     {
99         /* sub_sampling_x/y */
100         /* Currently the sub_sampling_x = 0, sub_sampling_y = 1 */
101         vp9_wb_write_bit(wb, 0);
102         vp9_wb_write_bit(wb, 0);
103         vp9_wb_write_bit(wb, 0); // unused
104     }
105 }

Seems not very correct.

### PR DESCRIPTION
**Pull request by SiewHoon**
According VP9 spec section 7.2.2 color config semantics,
both subsampling_x and subsampling_y should be 0 for YUV444.
Only YUV440 subsampling_x=0 and subsampling_y=1.

fixes #1074

Signed-off-by: Lim Siew Hoon <siew.hoon.lim@intel.com>

### CODE REVIEW

File: media_driver/linux/common/codec/ddi/media_libvpx_vp9.cpp [hunk 1]
```diff
@@ -97,9 +97,9 @@ void write_bitdepth_colorspace_sampling(uint32_t codecProfile,
         (codecProfile == VP9_PROFILE_3))
     {
         /* sub_sampling_x/y */
-        /* Currently the sub_sampling_x = 0, sub_sampling_y = 1 */
+        /* Currently the sub_sampling_x = 0, sub_sampling_y = 0 */
```
Comment (XinfengZhang) [inline media_driver/linux/common/codec/ddi/media_libvpx_vp9.cpp:100]: PROFILE1 and profile3, suppose should cover both 444 440 420?

Comment (SiewHoon) [reply media_driver/linux/common/codec/ddi/media_libvpx_vp9.cpp:100]: Only PROFILE 0 / PRFOFILE 2 is cover for 420.  PROFILE 1  and PROFILE 3 is cover both 440 and 444. This information are coming from vp9-bitstream-specification-v0.6-20160331-draft.pdf under section 7.2 Uncompressed header semantics.  Does the media driver side got support for VP9 encode YUV440?

Comment (XinfengZhang) [reply media_driver/linux/common/codec/ddi/media_libvpx_vp9.cpp:100]: accept it, because we does not support 440, so , always is 444.
