### PR TITLE
[Media Common] [VP] Remove unused include fixes #1549

### LINKED ISSUE #1549: [Bug]: va/va_dricommon.h: No such file or directory
### Which component impacted?

Build

### Is it regression? Good in old configuration?

Yes, it's good in old version - 22.6.2

### What happened?

Should have compiled against Libva 2.16.0

```
$ find . -name va_dricommon.h
./build.LibreELEC-Generic.x86_64-11.0-devel/build/libva-2.16.0/va/x11/va_dricommon.h
```

```
BUILD      media-driver (target)
    TOOLCHAIN      cmake (auto-detect)
Executing (target): cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/etc/cmake-x86_64-libreelec-linux-gnu.conf -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DBUILD_CMRTLIB=OFF -DBUILD_KERNELS=ON -DBUILD_TYPE=release -DENABLE_NONFREE_KERNELS=ON -DMEDIA_BUILD_FATAL_WARNINGS=ON -DMEDIA_RUN_TEST_SUITE=OFF /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/media-driver-22.6.3
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_INSTALL_PREFIX = /usr
-- Found PkgConfig: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/pkg-config (found version "0.29.2") 
-- Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB) 
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include  
-- Checking for module 'igdgmm>=12.0.0'
--   Found igdgmm, version 12.3.0
-- media -- PLATFORM = linux
-- media -- ARCH = 64
-- media -- CMAKE_CURRENT_LIST_DIR = /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/media-driver-22.6.3/media_driver
-- media -- INCLUDED_LIBS = 
-- media -- LIB_NAME = iHD_drv_video
-- media -- OUTPUT_NAME = 
-- media -- BUILD_TYPE/UFO_BUILD_TYPE/CMAKE_BUILD_TYPE = release/release/Release
-- media -- LIBVA_INSTALL_PATH = 
-- media -- MEDIA_VERSION = 22.6.3
-- Checking for module 'libva>=1.8.0'
--   Found libva, version 1.16.0
-- LIBVA_DRIVERS_PATH = /usr/lib/dri
-- Configuring done
-- Generating done
-- Build files have been written to: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/media-driver-22.6.3/.x86_64-libreelec-linux-gnu
Executing (target): ninja 

…

[335/1467] Building CXX object media_driver/CMakeFiles/iHD_drv_v....dir/__/media_softlet/linux/common/vp/ddi/ddi_vp_functions.cpp.o
FAILED: media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/__/media_softlet/linux/common/vp/ddi/ddi_vp_functions.cpp.o 

…

/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/media-driver-22.6.3/media_softlet/linux/common/vp/ddi/ddi_vp_functions.cpp:26:10: fatal error: va/va_dricommon.h: No such file or directory
   26 | #include <va/va_dricommon.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
[350/1467] Building CXX object media_driver/CMakeFiles/iHD_drv_v.../media_softlet/linux/common/ddi/media_libva_interface_next.cpp.o
ninja: build stopped: subcommand failed.
```

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

with commit https://github.com/intel/media-driver/commit/1e2afc600f35d35cd2790287516541bcbd32de61 compile fails with `media-driver-22.6.3/media_softlet/linux/common/vp/ddi/ddi_vp_functions.cpp:26:10: fatal error: va/va_dricommon.h: No such file or directory `

https://github.com/intel/media-driver/blob/0ba2777c8565d66065da53ea2c375b17fb4a066a/media_softlet/linux/common/vp/ddi/ddi_vp_functions.cpp#L26

### Debug Information

gmmlib: update to 22.3.1
media-driver: update to 22.6.3
libva: update to 2.16.0

### Do you want to contribute a patch to fix the issue?

Yes.

### PR DESCRIPTION
**Pull request by heitbaum**
[Media Common] [VP] dont include va_dricommon.h on non X11 builds

<va/va_dricommon.h> is unavailable and not in non-X11 libva 2.16.0

- Fixes #1549 

tested with GBM build. 

Signed-off-by: Rudi Heitbaum <rudi@heitbaum.com>

### CODE REVIEW

**Comment by heitbaum** [comment]
Also build tested with X11

BUILD      media-driver (target)
    TOOLCHAIN      cmake (auto-detect)
Executing (target): cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/toolchain/etc/cmake-x86_64-libreelec-linux-gnu.conf -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_CMRTLIB=OFF -DBUILD_KERNELS=ON -DBUILD_TYPE=release -DENABLE_NONFREE_KERNELS=ON -DMEDIA_BUILD_FATAL_WARNINGS=ON -DMEDIA_RUN_TEST_SUITE=OFF /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/build/media-driver-22.6.3
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_INSTALL_PREFIX = /usr
CMake Warning at Tools/bldsys/include/bs_base_utils.cmake:81 (message):
  Inconsistent: BUILD_TYPE="release" vs CMAKE_BUILD_TYPE="MinSizeRel"
Call Stack (most recent call first):
  Tools/bldsys/bs_init.cmake:35 (bs_check_build_type)
  media_driver/CMakeLists.txt:69 (include)


-- Found PkgConfig: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/toolchain/bin/pkg-config (found version "0.29.2") 
-- Found X11: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include   
-- Looking for XOpenDisplay in /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libX11.so;/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libXext.so
-- Looking for XOpenDisplay in /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libX11.so;/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include  
-- Checking for module 'igdgmm>=12.0.0'
--   Found igdgmm, version 12.3.0
-- media -- PLATFORM = linux
-- media -- ARCH = 64
-- media -- CMAKE_CURRENT_LIST_DIR = /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/build/media-driver-22.6.3/media_driver
-- media -- INCLUDED_LIBS = 
-- media -- LIB_NAME = iHD_drv_video
-- media -- OUTPUT_NAME = 
-- media -- BUILD_TYPE/UFO_BUILD_TYPE/CMAKE_BUILD_TYPE = release/release/Release
-- media -- LIBVA_INSTALL_PATH = 
-- media -- MEDIA_VERSION = 22.6.3
-- media -- X11 Found
-- Checking for module 'libva-x11'
--   Found libva-x11, version 1.16.0
-- media -- LIBVAX11 Found
-- Checking for module 'libva>=1.8.0'
--   Found libva, version 1.16.0
-- LIBVA_DRIVERS_PATH = /usr/lib/dri
-- Configuring done
-- Generating done
-- Build files have been written to: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/build/media-driver-22.6.3/.x86_64-libreelec-linux-gnu
Executing (target): ninja 
[1468/1468] Linking CXX shared library media_driver/iHD_drv_video.so
[0/1] Install the project...

File: media_softlet/linux/common/vp/ddi/ddi_vp_functions.cpp [hunk 1]
```diff
@@ -23,7 +23,9 @@
 //! \file     ddi_vp_functions.cpp
 //! \brief    ddi vp functions implementaion.
 //!
+#if defined(X11_FOUND)
 #include <va/va_dricommon.h>
+#endif
```
Comment (Jexu) [inline media_softlet/linux/common/vp/ddi/ddi_vp_functions.cpp:28]: You could remove this include since header "media_libva_putsurface_linux.h" has been included in line39.

Comment (heitbaum) [reply media_softlet/linux/common/vp/ddi/ddi_vp_functions.cpp]: Thanks for the reivew ad comments. Updated

**Review by Jexu — APPROVED** [review]

**Comment by Nexarian** [comment]
Are you sure you added the `#if defined(X11_FOUND)` for the header as described in the issue? I don't see it in the commit...

**Comment by heitbaum** [comment]
> Are you sure you added the `#if defined(X11_FOUND)` for the header as described in the issue? I don't see it in the commit...

removed as requested - https://github.com/intel/media-driver/pull/1550#discussion_r1029954734

**Comment by bkuhls** [comment]
There is another PR which fixes the problem: https://github.com/intel/media-driver/pull/1555

**Review by XinfengZhang — APPROVED** [review]
