### PR TITLE
[Media Common] Fix include when building with -DGEN8=OFF

### LINKED ISSUE #1065: Build fail with -DGEN8=OFF or -DGEN10=OFF
When building media driver sources from latest release tag "intel-media-20.3.0":
`cmake -G Ninja  -DGEN8=OFF -DGEN9=ON -DGEN10=OFF -DGEN11=ON -DGEN12=ON .  &&  ninja`

The build fails with:
```
In file included from ../media_driver/agnostic/common/cm/cm_command_buffer.cpp:44:
../media_driver/agnostic/gen12/cm/cm_hal_g12.h:31:10: fatal error: mhw_render_hwcmd_g8_X.h: No such file or directory
   31 | #include "mhw_render_hwcmd_g8_X.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### LINKED ISSUE #1301: Building with -DGEN8=OFF fails
## System information
- GPU platform enabling for new feature: Build configuration request and not specific to hardware.
- Host machine if it's descreted card: Not a discrete card.
- libva/libva-utils/gmmlib/media-driver version you are using? Top of master branches
- Are you willing to contribute it?(Yes/No) Yes

### Describe the feature and expected behavior
Building with ```-DGEN8=OFF``` should complete. It currently fails on an include.

```
cmake -DGEN8=OFF ../
make -j$(nproc)
<snip>
[ 21%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/codec/hal/codechal_decode_sfc_hevc.cpp.o
[ 21%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/codec/hal/codechal_decode_jpeg.cpp.o
[ 21%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/codec/hal/codechal_mmc_decode_hevc.cpp.o
In file included from /mnt/data/media-driver/media_driver/agnostic/common/cm/cm_execution_adv.cpp:47:
/mnt/data/media-driver/media_driver/agnostic/gen12/cm/cm_hal_g12.h:32:10: fatal error: mhw_render_hwcmd_g8_X.h: No such file or directory
   32 | #include "mhw_render_hwcmd_g8_X.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:531: media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_execution_adv.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /mnt/data/media-driver/media_driver/agnostic/common/cm/cm_command_buffer.cpp:44:
/mnt/data/media-driver/media_driver/agnostic/gen12/cm/cm_hal_g12.h:32:10: fatal error: mhw_render_hwcmd_g8_X.h: No such file or directory
   32 | #include "mhw_render_hwcmd_g8_X.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:674: media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_command_buffer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:378: media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

### Customer usage and impact for this feature
The final driver shared object is unnecessarily large. For example in Chrome OS we could disable media generations or specific SoC families that are not applicable.
```
ed@ebaker-desk:/mnt/data/media-driver/build$ du -sm media_driver/iHD_drv_video.so 
223     media_driver/iHD_drv_video.so
ed@ebaker-desk:/mnt/data/media-driver/build$ strip media_driver/iHD_drv_video.so 
ed@ebaker-desk:/mnt/data/media-driver/build$ du -sm media_driver/iHD_drv_video.so 
36      media_driver/iHD_drv_video.so
```

### PR DESCRIPTION
**Pull request by edwarddavidbaker**
This commit address the following compilation error when building with
cmake -DGEN8=OFF. Partially fixes #1065.
    
media-driver/media_driver/agnostic/gen12/cm/cm_hal_g12.h:32:10:
fatal error: mhw_render_hwcmd_g8_X.h: No such file or directory

### CODE REVIEW

File: media_driver/agnostic/gen12/cm/cm_hal_g12.h [hunk 1]
```diff
@@ -28,7 +28,7 @@
 #define _CM_HAL_G12_H_
 
 #include "cm_hal.h"
-#include "mhw_render_hwcmd_g8_X.h"
+#include "mhw_render_hwcmd_g12_X.h"
```
Comment (dvrogozh) [inline media_driver/agnostic/gen12/cm/cm_hal_g12.h:31]: It seems driver can be successfully built even if this include file be removed from here. Is it actually needed?

Comment (edwarddavidbaker) [reply media_driver/agnostic/gen12/cm/cm_hal_g12.h:31]: I'll need to study the actual includes generated by CMake, but I suspect we get "lucky" somehow? Seems like we should include the header since `mhw_render_g12_X` is used in `cm_hal_gen12.cpp`.

Comment (edwarddavidbaker) [reply media_driver/agnostic/gen12/cm/cm_hal_g12.h:31]: Whoops, reading too quickly. `mhw_render_g12_X.h` is already included in `cm_hal_gen12.cpp`. We should go with your comment and delete the include from `cm_hal_g12.h`. Thanks.

**Review by dvrogozh — APPROVED** [review]
Looks good.

**Review by XinfengZhang — APPROVED** [review]
